apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dashboard-frontend
  namespace: k8s-readonly-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-dashboard-frontend
  template:
    metadata:
      labels:
        app: k8s-dashboard-frontend
    spec:
      containers:
        - name: frontend
          image: example/k8s-dashboard-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
