apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-dashboard
  namespace: k8s-readonly-dashboard
spec:
  rules:
    - host: k8s-dashboard.internal.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: k8s-dashboard-backend
                port:
                  number: 8000
          - path: /health
            pathType: Exact
            backend:
              service:
                name: k8s-dashboard-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-dashboard-frontend
                port:
                  number: 80
