apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard-backend
  namespace: k8s-readonly-dashboard
spec:
  selector:
    app: k8s-dashboard-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard-frontend
  namespace: k8s-readonly-dashboard
spec:
  selector:
    app: k8s-dashboard-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
